---
name: hello-http
services:
  hello:
    image: bob2606/hello-http:0.8.29
    container_name: hello
    hostname: hello
    environment:
      - PORT=80
    ports:
      - 80:80
    networks:
      hellonet:
        ipv4_address: 10.10.10.200
    volumes:
      - ./status:/var/lib/hello-http/status
      - data:/var/lib/hello-http/data
    restart: unless-stopped

networks:
  hellonet:
    driver_opts:
      com.docker.network.bridge.name: hellonet0
    ipam:
      config:
        - subnet: 10.10.10.0/24
          gateway: 10.10.10.254

volumes:
  data:
