---
services:
  hello:
    image: bob2606/hello-http:0.8.29
    container_name: hello
    hostname: hello
    environment:
      - PORT=80
    ports:
      - 80:80
    networks:
      hellonet:
        ipv4_address: 10.10.10.200
    volumes:
      - ./status:/var/lib/hello-http/status
    restart: unless-stopped

networks:
  hellonet:
    external: true
