---
name: proxy

services:
  proxy:
    image: traefik:v2.9
    container_name: proxy
    hostname: traefik
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - ./traefik.yml:/etc/traefik/traefik.yml
      - /run/docker.sock:/run/docker.sock
    restart: unless-stopped
    networks:
      proxynet:

  errorhandler:
    image: nginx:1.28
    container_name: errorhandler
    volumes:
      - ./html:/usr/share/nginx/html
    networks:
      proxynet:
    labels:
      - traefik.enable=true
      - traefik.http.services.errorhandler.loadbalancer.server.port=80

networks:
  proxynet:
    name: proxynet
