---
name: hello-http

services:
  hello-1:
    image: bob2606/hello-http:0.8.29
    container_name: hello-1
    hostname: hello-1
    environment:
      PORT: 80
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxynet
      - traefik.http.services.hello_1.loadbalancer.server.port=80
      - traefik.http.routers.hello_1.rule=Host(`hello-1.stage.local`)
    networks:
      proxynet:

  hello-2:
    image: bob2606/hello-http:0.8.29
    container_name: hello-2
    hostname: hello-2
    environment:
      PORT: 80
    restart: unless-stopped
    networks:
      proxynet:
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxynet
      - traefik.http.services.hello_2.loadbalancer.server.port=80
      - traefik.http.routers.hello_2.rule=PathPrefix(`/hello-2`)

  hello-3:
    image: bob2606/hello-http:0.8.29
    container_name: hello-3
    hostname: hello-3
    environment:
      PORT: 80
    restart: unless-stopped
    networks:
      proxynet:
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxynet
      - traefik.http.services.hello_3.loadbalancer.server.port=80

networks:
  proxynet:
    external: true
