---
x-logging: &default-logging
  logging:
    driver: json-file
    options:
      max-size: 10m
      max-file: 1

services:
  www:
    image: nginx:1.28
    hostname: nginx
    ports:
      - 80:80
    <<: *default-logging
    networks:
      lemp:
    volumes:
      - nginx-conf:/etc/nginx/conf.d:ro
      - html:/usr/share/nginx/html:ro

  php:
    image: php:8.2-fpm
    hostname: php
    <<: *default-logging
    networks:
      lemp:
    volumes:
      - html:/var/www/html:ro

networks:
  lemp:
    ipam:
      config:
        - subnet: 172.30.0.0/24

volumes:
  html:
    driver_opts:
      type: nfs
      o: addr=192.168.56.210,vers=4.2
      device: ":/html"
  nginx-conf:
    driver_opts:
      type: nfs
      o: addr=192.168.56.210,vers=4.2
      device: ":/nginx-conf"
