---
name: lemp

services:
  www:
    image: nginx:${NGINX_IMAGE_TAG}
    container_name: web
    hostname: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d
      - ./html:/usr/share/nginx/html
    restart: unless-stopped
    networks:
      lempnet:
        ipv4_address: ${LEMPNET_SUBNET}.${NGINX_IPV4}

  php:
    image: php:${PHP_IMAGE_TAG}
    container_name: php
    hostname: php
    volumes:
      - ./html:/var/www/html
    restart: unless-stopped
    networks:
      lempnet:
        ipv4_address: ${LEMPNET_SUBNET}.${PHP_IPV4}

  db:
    image: mariadb:${MARIADB_IMAGE_TAG}
    container_name: mariadb
    hostname: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_DATABASE=stage
    volumes:
      - mariadb:/var/lib/mysql
    restart: unless-stopped
    networks:
      lempnet:
        ipv4_address: ${LEMPNET_SUBNET}.${MARIADB_IPV4}

networks:
  lempnet:
    ipam:
      config:
        - subnet: ${LEMPNET_SUBNET}.0/${LEMPNET_CIDR}
          gateway: ${LEMPNET_SUBNET}.254
    driver_opts:
      com.docker.network.bridge.name: lempnet0

volumes:
  mariadb:
