---
name: lemp

services:
  www:
    image: nginx:1.28
    container_name: web
    hostname: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d
      - ./html:/usr/share/nginx/html
    restart: unless-stopped
    networks:
      lempnet:
        ipv4_address: 172.30.0.100

  php:
    image: php:8.2-fpm
    container_name: php
    hostname: php
    volumes:
      - ./html:/var/www/html
    restart: unless-stopped
    networks:
      lempnet:
        ipv4_address: 172.30.0.150

  db:
    image: mariadb:10.8
    container_name: mariadb
    hostname: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=azerty
      - MARIADB_DATABASE=stage
    volumes:
      - mariadb:/var/lib/mysql
    restart: unless-stopped
    networks:
      lempnet:
        ipv4_address: 172.30.0.200

networks:
  lempnet:
    ipam:
      config:
        - subnet: 172.30.0.0/16
          gateway: 172.30.0.254
    driver_opts:
      com.docker.network.bridge.name: lempnet0

volumes:
  mariadb:
